__require_root () was split
__require_root_priv fails loudly if we don't have privileges
__has_root_priv exits with 1 if we don't have privileges

diff --git a/lib-btr/common b/lib-btr/common
--- a/lib-btr/common
+++ b/lib-btr/common
@@ -188,3 +188,15 @@ __read_targets () {
         tr "," "\n" <<< "$1"
     fi
 }
+
+__has_root_priv () {
+    [[ -w "$butter_root/$butter_host" ]]
+}
+
+# Fails loudly if we don't have a root directory for butter
+# Fails loudly if we don't have enough privileges.
+__require_root_priv () {
+    if ! __has_root_priv; then
+        __fatal "Can't write to $butter_root"
+    fi
+}
